### ISSUE TITLE
SignalR - System.ArgumentNullException: Value cannot be null. Parameter name: connectionId

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#1171]
#### Describe the Issue
Using **Sync-Element** in UD-Input endpoint, I get the following error message. 

System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: connectionId
at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.SendConnectionAsync(String connectionId, String methodName, Object[] args, CancellationToken cancellationToken)
at Microsoft.AspNetCore.SignalR.Internal.SingleClientProxy`1.SendCoreAsync(String method, Object[] args, CancellationToken cancellationToken)
at Microsoft.AspNetCore.SignalR.ClientProxyExtensions.SendAsync(IClientProxy clientProxy, String method, Object arg1, CancellationToken cancellationToken)
at UniversalDashboard.DashboardHubContextExtensions.<SyncElement>d__15.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at UniversalDashboard.Cmdlets.SyncElementCommand.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: connectionId
at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.SendConnectionAsync(String connectionId, String methodName, Object[] args, CancellationToken cancellationToken)
at Microsoft.AspNetCore.SignalR.Internal.SingleClientProxy`1.SendCoreAsync(String method, Object[] args, CancellationToken cancellationToken)
at Microsoft.AspNetCore.SignalR.ClientProxyExtensions.SendAsync(IClientProxy clientProxy, String method, Object arg1, CancellationToken cancellationToken)
at UniversalDashboard.DashboardHubContextExtensions.<SyncElement>d__15.MoveNext()<---

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Click on the Hamburger
3. Press ALT-F4
4. Browser Closes...

#### Expected behavior
Targeted element should be synced.
The problem does not occurs if I create a button and put the Sync-UDElement within it instead.

This should be what happens

![image](https://aws1.discourse-cdn.com/standard11/uploads/universaldashboard/original/1X/9236e2319f16b94197b0783b98a4f5977bbabae3.gif)

(I was somewhat able to make it work when answering a question on the forums but it does not work anymore. The behavior seems inconsistent)

#### Script Sample
```

Import-Module UniversalDashboard -RequiredVersion 2.6.0
$page = New-UDPage -Name "OpenFiles"  -Content {
    New-UDInput -Title "Enter Partial file name" -Endpoint {
        param(
            [string]$phrase
        )

        $a = Get-ChildItem -Path "$($env:USERPROFILE)\desktop"

        $Cache:FilesFound = $a | Where-Object -Property fullname -Like "*$phrase*" -erroraction stop 
            try {
                Sync-UDElement -Id 'results'
                }
            catch {
              $Cache:Errors = $_
            }

    }

    New-UDElement -Id 'results' -Tag 'div' -Endpoint {
        if ($Cache:FilesFound -ne $null) {
            New-UDTable -Id 'results'  -Title "Files" -Header @("name", "FullName ") -Endpoint {
                $Cache:FilesFound | Out-UDTableData -Property @("name", "FullName")
            }    
        }
    
    }

    new-udcard -Title '.' -Text $Cache:Errors.Exception

}

$dash  = New-UDDashboard -pages $page
Start-UDDashboard -Dashboard $dash -Port 12222 -Force


```

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.) IIS / VsCode

#### Additional context
Reference:
 https://forums.universaldashboard.io/t/result-of-new-udinput-to-be-output-in-new-udtable-or-new-udgrid-below/1280/2

(even though it worked in the referenced link,, I get mostly failures.)

**Comment by adamdriscoll** [comment]
This is resolved with the latest PR. There were some pretty big issues with Connection\Session management in UD that should be solved now.
