### ISSUE TITLE
System.MissingMethodException: Method not found: 'System.Nullable`1<Boolean> Newtonsoft.Json.JsonReader.ReadAsBoolean()'

### ISSUE THREAD

**Issue by dotraphael** [ironmansoftware/universal-dashboard#275]
trying the community edition and getting (UD Log attached)
[Ud.log](https://github.com/ironmansoftware/universal-dashboard/files/2218466/Ud.log)

Application startup exception: System.MissingMethodException: Method not found: 'System.Nullable`1<Boolean> Newtonsoft.Json.JsonReader.ReadAsBoolean()'.
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadCompilationOptions(JsonTextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JsonTextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly, IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at UniversalDashboard.ServerStartup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

example i'm using:
import-module UniversalDashboard.Community
import-module MSOnline

$HTTPPort = 10001

$Colors = @{
    BackgroundColor = "#252525"
    FontColor = "#FFFFFF"
}

$AlternateColors = @{
    BackgroundColor = "#4081C9"
    FontColor = "#FFFFFF"
}

$ScriptColors = @{
    BackgroundColor = "#5A5A5A"
    FontColor = "#FFFFFF"
}

$NavBarColor = "#FF1c1c1c"
$NavBarFontColor = "#FF55b3ff"
$BackgroundColor = "#FF333333"
$FontColor = "#FFFFFFF"

$NavBarTitle = 'Test'

$NavBarLinks = @(
    (New-UDLink -Text "Twitter" -Url "https://twitter.com/dotraphael/" -Icon twitter),
    (New-UDLink -Text "LinkedIn" -Url "https://www.linkedin.com/in/dotraphael/" -Icon linkedin),
    (New-UDLink -Text "Blog" -Url "https://thedesktopteam.com" -Icon bookmark )
)

$HomePage = New-UDPage -Name "Home" -Icon home -Content {
    New-UDRow {
        New-UDColumn -Size 12 {
            New-UDHtml -Markup "<div class='center-align white-text'><h3>Beautiful dashboards. All PowerShell.</h3></h3><h5>Universal Dashboard is a cross-platform PowerShell module for developing and hosting web-based, interactive dashboards.</h5></div>"
        }
    }
}

$DashboardContent = New-UDDashboard -Title $NavBarTitle -NavBarColor $NavBarColor -NavBarFontColor $NavBarFontColor -BackgroundColor $BackgroundColor -FontColor $FontColor -Pages @(
    $HomePage#,
    #$Component
) #-CyclePages -CyclePagesInterval 10

Start-UDDashboard -Dashboard $DashboardContent -Name "CE-Dashboard" -Port $HTTPPort -Wait | Out-Null #-AutoReload 
Get-UDDashboard | Stop-UDDashboard

**Comment by adamdriscoll** [comment]
Can you list the modules you have loaded? It seems like something else loaded a version of Json.NET that is conflicting with UD.

**Comment by adamdriscoll** [comment]
If you can still reproduce, please reopen this issue.

**Comment by dotraphael** [comment]
i have just updated to beta2 and issue is still happening.

**Comment by adamdriscoll** [comment]
@dotraphael Ok. Thanks. 

Can you please run this after you receive this error? 


```
Get-Module
$PSVersionTable
```

**Comment by dotraphael** [comment]
before:
PS C:\WINDOWS\system32> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...


PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


after:
PS C:\Temp> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   1.1.166.0  MSOnline                            {Add-MsolAdministrativeUnitMember, Add-MsolForeignGroupToR...
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...
Script     2.0.0      UniversalDashboard.Community        {Add-UDElement, Clear-UDElement, ConvertTo-JsonEx, Disable...


PS C:\Temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


thanks
