### ISSUE TITLE
[Start-UDRestApi] HTTP Error 502.5 - Process Failure 

### ISSUE THREAD

**Issue by LaurentDardenne** [ironmansoftware/universal-dashboard#404]
I have migrate UD from 1.7 to 2.1 under IIS, but i get an error when i call an API :

UD version 2.0.1 (UniversalDashboard & UniversalDashboard.Community)

Windows Server 2008 R2 Standard SP1

IIS V 7.5.7600.16385

May be  related to this issue https://github.com/ironmansoftware/universal-dashboard/issues/389

Dotnet :
```
PS C:\temp> dotnet --version
2.1.403

PS C:\temp> dotnet --list-sdks

2.1.403 [C:\Program Files\dotnet\sdk]
PS C:\temp> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

PS C:\temp> Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4"
    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4


Name                           Property
----                           --------
Client                         Version       : 4.7.02558
                               TargetVersion : 4.0.0
                               Install       : 1
                               MSI           : 1
                               Servicing     : 0
                               InstallPath   : C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
                               Release       : 461310
Full                           Version       : 4.7.02558
                               TargetVersion : 4.0.0
                               Install       : 1
                               MSI           : 1
                               Servicing     : 0
                               InstallPath   : C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
                               Release       : 461310

```
PowerShell version :
```Powershell
$psversiontable :
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
The call :
```Powershell
# New-UDEndpoint -Url "/v1/Request/Create" -Method "POST" -Endpoint {..}
Invoke-RestMethod -uri http://MySite:1002/api/v1/Request/Create -Method POST -Body (@{Data='DATA' } | ConvertTo-Json)

$error[0]
Invoke-RestMethod :                                      
IIS 502.5 Error                       
HTTP Error 502.5 - Process Failure                           
Common causes of this issue:               
The application process failed to start
The application process started but then stopped
The application process started but

failed to listen on the configured port
Troubleshooting steps:                
Check the system event log for error messages
...

At line:1 char:1
+ Invoke-RestMethod -uri http://mySite:1002/api/v1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```
Exception information :
```Powershell
$error[0].Exception|select *

Status         : ProtocolError
Response       : System.Net.HttpWebResponse
Message        : The remote server returned an error: (502) Bad Gateway.
Data           : {}
InnerException :
TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
HelpLink       :
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079
```

Contains of Application eventLog :
```
EventID            : 1000
MachineName        : MyMachine
Data               : {}
Index              : 198064
Category           : (0)
CategoryNumber     : 0
EntryType          : Error
Message            : Application 'MACHINE/WEBROOT/APPHOST/MySite' with physical root 'C:\inetpub\wwwroot\MySite\' failed to start process with commandline
                     'C:\inetpub\wwwroot\MySite\net471\universaldashboard.server.exe ', ErrorCode = '0x80004005 : ff.
Source             : IIS AspNetCore Module
ReplacementStrings : {Application 'MACHINE/WEBROOT/APPHOST/MySite' with physical root 'C:\inetpub\wwwroot\MySite\' failed to start process with commandline
                     'C:\inetpub\wwwroot\MySite\net471\universaldashboard.server.exe ', ErrorCode = '0x80004005 : ff.}
InstanceId         : 1000
TimeGenerated      : 10/26/2018 10:32:14 AM
TimeWritten        : 10/26/2018 10:32:14 AM
UserName           :
Site               :
Container          :

EventID            : 1001
MachineName        : MyMachine
Data               : {}
Index              : 198063
Category           : (0)
CategoryNumber     : 0
EntryType          : Information
Message            : Fault bucket , type 0
                     Event Name: CLR20r3
                     Response: Not available
                     Cab Id: 0

                     Problem signature:
                     P1: universaldashboard.server.exe
                     P2: 1.0.0.0
                     P3: a470e158
                     P4: UniversalDashboard.Server
                     P5: 1.0.0.0
                     P6: a470e158
                     P7: 1
                     P8: d8
                     P9: System.Exception
                     P10:

                     Attached files:
                     C:\Windows\Temp\WERBE92.tmp.appcompat.txt
                     C:\Windows\Temp\WERBF00.tmp.WERInternalMetadata.xml
                     C:\Windows\Temp\WERBF01.tmp.hdmp
                     C:\Windows\Temp\WERD1E6.tmp.mdmp

                     These files may be available here:
                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_universaldashboa_8b76634bcd801ea3d655147de26f521b3174a3e_cab_1396d2dd

                     Analysis symbol:
                     Rechecking for solution: 0
                     Report Id: a00b294c-d8f9-11e8-ba7b-005056b166a2
                     Report Status: 4
Source             : Windows Error Reporting
ReplacementStrings : {, 0, CLR20r3, Not available...}
InstanceId         : 1001
TimeGenerated      : 10/26/2018 10:32:14 AM
TimeWritten        : 10/26/2018 10:32:14 AM
UserName           :
Site               :
Container          :

EventID            : 1000
MachineName        : MyMachine
Data               : {}
Index              : 198062
Category           : Application Crashing Events
CategoryNumber     : 100
EntryType          : Error
Message            : Faulting application name: universaldashboard.server.exe, version: 1.0.0.0, time stamp: 0xa470e158
                     Faulting module name: KERNELBASE.dll, version: 6.1.7601.24231, time stamp: 0x5b6db5dd
                     Exception code: 0xe0434352
                     Fault offset: 0x000000000001a06d
                     Faulting process id: 0x1644
                     Faulting application start time: 0x01d46d0661e8e689
                     Faulting application path: C:\inetpub\wwwroot\MySite\net471\universaldashboard.server.exe
                     Faulting module path: C:\Windows\system32\KERNELBASE.dll
                     Report Id: a00b294c-d8f9-11e8-ba7b-005056b166a2
Source             : Application Error
ReplacementStrings : {universaldashboard.server.exe, 1.0.0.0, a470e158, KERNELBASE.dll...}
InstanceId         : 1000
TimeGenerated      : 10/26/2018 10:32:08 AM
TimeWritten        : 10/26/2018 10:32:08 AM
UserName           :
Site               :
Container          :


EventID            : 1026
MachineName        : MyMachine
Data               : {}
Index              : 198061
Category           : (0)
CategoryNumber     : 0
EntryType          : Error
Message            : Application: universaldashboard.server.exe
                     Framework Version: v4.0.30319
                     Description: The process was terminated due to an unhandled exception.
                     Exception Info: System.Exception
                        at UniversalDashboard.DashboardManager.Start()
                        at UniversalDashboard.Program.Main(System.String[])


Source             : .NET Runtime
ReplacementStrings : {Application: universaldashboard.server.exe
                     Framework Version: v4.0.30319
                     Description: The process was terminated due to an unhandled exception.
                     Exception Info: System.Exception
                        at UniversalDashboard.DashboardManager.Start()
                        at UniversalDashboard.Program.Main(System.String[])

                     }
InstanceId         : 1026
TimeGenerated      : 10/26/2018 10:32:08 AM
TimeWritten        : 10/26/2018 10:32:08 AM
UserName           :
Site               :
Container          :
``` 
The version 1.7 works on the same IIS Server.

Additionnal 'tests' :
```
PS C:\inetpub\wwwroot\MySite\netstandard2.0> dotnet .\UniversalDashboard.dll
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\inetpub\wwwroot\MySite\netstandard2.0\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\inetpub\wwwroot\MySite\netstandard2.0\UniversalDashboard.runtimeconfig.json file specifying the appropriate framework.

PS C:\inetpub\wwwroot\MySite\net471> .\UniversalDashboard.Server.exe
Unhandled Exception: System.Exception: Failed to start dashboard
   at UniversalDashboard.DashboardManager.Start()
   at UniversalDashboard.Program.Main(String[] args)
```

**Comment by adamdriscoll** [comment]
Can you pleas try installing .NET framework 4.7.2?

**Comment by LaurentDardenne** [comment]
I installed the NDP472-DevPack-ENU .exe version without success, I get the same error.

**Comment by adamdriscoll** [comment]
Yep. The EndpointInitialization change was a breaking change in 2.0. Can you please try this build when it is complete? 

https://ci.appveyor.com/project/adamdriscoll/universal-dashboard/builds/19944952

I've added better error reporting in UniversalDashboard.Server.exe. You will see errors in the console and in Event Viewer in the Application log under Universal Dashboard. 

![image](https://user-images.githubusercontent.com/1256531/47791637-bfe3df80-dcdf-11e8-8a2c-6d029bcebb38.png)

Could you also enable UDLogging? 

```
Enable-UDLogging -FilePath C:\myLogPath.txt
```

**Comment by LaurentDardenne** [comment]
I'm trying to test that next week.

**Comment by LaurentDardenne** [comment]
I do not see any improvement with this compilation, I have the same error message and no extra entries are created in the eventlog.

**Comment by adamdriscoll** [comment]
@LaurentDardenne After playing with this more, I was able to reproduce by uninstalling the ASP.NET Core Hosting Bundle (which was renamed from the ASP.NET Core Module). 

https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.5-windows-hosting-bundle-installer

I am updating the documentation with this download link. Can you please give that a shot?

**Comment by LaurentDardenne** [comment]
No improvement after installing the ASP.NET Core Hosting Bundle 2.1.5.

**Comment by adamdriscoll** [comment]
@LaurentDardenne Just to verfiy: You are using the `-Wait` parameter on `Start-UDRestApi` or `Start-UDDashboard`?

**Comment by LaurentDardenne** [comment]
Sorry for the confusion.
I use -Wait parameter on Start-UDRestApi.
I can  test again on a new server 2012 with a fresh install.

Now I know that this type of error is not an error on the IIS site I can expect a new version that implements error handling.
I close this issue. Thank you for your help.
