### ISSUE TITLE
Errors when starting a Dashboard on MacOS

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#61]
I'm trying to run the script below taken from there : https://github.com/apetitjean/Universal-Dashboard

The script works fine, but I got errors at startup. Could you please fix this?
Thanks Adam!

PS > ./01-HelloWorld.ps1                                  
Exception while loading assembly Microsoft.AspNetCore.DataProtection.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182

Exception while loading assembly Microsoft.AspNetCore.DataProtection.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182

Exception while loading assembly Microsoft.AspNetCore.Mvc.Abstractions.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182

Exception while loading assembly Microsoft.AspNetCore.Mvc.Abstractions.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.2/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182

Name       Port Running
----       ---- -------
Dashboard0 8081    True

**Comment by adamdriscoll** [comment]
@apetitjean Does the dashboard work after you see this error?

**Comment by apetitjean** [comment]
Yes it work.

2018-05-01 1:35 GMT+02:00 Adam Driscoll <notifications@github.com>:
