### ISSUE TITLE
 Application startup exception: System.MissingMethodException: Method not found: 'System.Nullable`1<Boolean> Newtonsoft.Json.JsonReader.ReadAsBoolean()'.

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#80]
> Application startup exception: System.MissingMethodException: Method not found: 'System.Nullable`1<Boolean> Newtonsoft.Json.JsonReader.ReadAsBoolean()'.
>    at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.ReadCompilationOptions(JsonTextReader reader)
>    at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JsonTextReader reader)
>    at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
>    at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly, IDependencyContextReader reader)
>    at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
>    at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
>    at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
>    at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
>    at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
>    at PowerShellProTools.UniversalDashboard.ServerStartup.ConfigureServices(IServiceCollection services)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by adamdriscoll** [comment]
Cannot reproduce.

**Comment by artvandelay440** [comment]
Hi Adam, I can reproduce a null NewtonsoftJson method similar to this bug on UD v2.0.1 and Ubuntu Server 18.04 LTS

The same dashboard works fine under Windows 10 Build 1803 and Powershell 5.1


Environment:
````
PS /home/nate/dashboards> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Linux 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

````
PS /home/nate/dashboards> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
````

Full `Enable-UDLogging -Verbose` Output:

````
New-UDPage : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:13 char:13
+ $HomePage = New-UDPage -Name "Home" -Icon home -Content {
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-UDPage], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,UniversalDashboard.Cmdlets.NewPageCommand

New-UDPage : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:20 char:10
+ $Page1 = New-UDPage -Name "Page 1" -Icon ticket -Content {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-UDPage], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,UniversalDashboard.Cmdlets.NewPageCommand

New-UDPage : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:28 char:10
+ $Page2 = New-UDPage -Name "Page 2" -icon ticket -Content {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-UDPage], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,UniversalDashboard.Cmdlets.NewPageCommand

New-UDPage : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:35 char:10
+ $Page3 = New-UDPage -Name "Page 3" -Icon desktop -Content {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-UDPage], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,UniversalDashboard.Cmdlets.NewPageCommand

New-UDPage : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:43 char:18
+ ... mic01Page = New-UDPage -Url "/dynamic/:dynamic01" -Icon newspaper_o - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-UDPage], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,UniversalDashboard.Cmdlets.NewPageCommand

New-UDLink : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:59 char:30
+ ...                    (New-UDLink -Text "Home" -Icon home -Url "/Home"),
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-UDLink], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,UniversalDashboard.Cmdlets.NewLinkCommand

17:11:06 DashboardColor Parse - hexOrName = #FFFFFF
17:11:06 DashboardColor Parse - iColorInt = -1
17:11:06 DashboardColor DashboardColor - argb = -1
17:11:06 ColorExtensions rgba(255, 255, 255, 1)
17:11:06 DashboardColor Parse - hexOrName = #333333
17:11:06 DashboardColor Parse - iColorInt = -13421773
17:11:06 DashboardColor DashboardColor - argb = -13421773
17:11:06 ColorExtensions rgba(51, 51, 51, 1)
17:11:06 DashboardColor Parse - hexOrName = #F9F9F9
17:11:06 DashboardColor Parse - iColorInt = -394759
17:11:06 DashboardColor DashboardColor - argb = -394759
17:11:06 ColorExtensions rgba(249, 249, 249, 1)
17:11:06 DashboardColor Parse - hexOrName = #333333
17:11:06 DashboardColor Parse - iColorInt = -13421773
17:11:06 DashboardColor DashboardColor - argb = -13421773
17:11:06 ColorExtensions rgba(51, 51, 51, 1)
New-UDDashboard : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:68 char:14
+ $Dashboard = New-UDDashboard @DashboardParameters @NavColorsDark
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-UDDashboard], ParameterBindingException
+ FullyQualifiedErrorId : AmbiguousParameterSet,UniversalDashboard.Cmdlets.NewDashboardCommand

Start-UDDashboard : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At /home/nate/dashboards/HomeLab_UDDashboard.ps1:69 char:1
+ Start-UDDashboard -Dashboard $Dashboard -Port "8080" -AutoReload
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Start-UDDashboard], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,UniversalDashboard.Cmdlets.StartDashboardCommand
````

**Comment by tsmithbtzels** [comment]
I was able to reproduce this on Server 2016.  Brand new install.  UD was working fine.  Installed Exchange 2010 SP3 (for the management tools), then UD would show this error.  Uninstalled Exchange, UD is fine again.

**Comment by cbates291** [comment]
I am also getting this error. All UD dashboards were working fine. Then I rebooted and it started giving this error.

**Comment by fsckr** [comment]
I just installed this module and getting the same error has there been any updates on this?

**Comment by ArtisanByteCrafter** [comment]
What version of Powershell are you all on? I believe Adam figured out that it was an external dependency in powershell itself. Currently running UD 2.3.2 and pwsh 6.2 on ubuntu and it's working fine.

**Comment by Richt3rScal3** [comment]
Any updates here? UD works some days, and then on restart it immediately goes back to this error.

**Comment by cbates291** [comment]
I noticed the issue when I installed the 2008 exchange console which
updates modules and .net. I think this conflicts or installs another
version or something because after uninstall it works fine

**Comment by Richt3rScal3** [comment]
The issue seems to be with Exchange/MSOnline and UD conflicting. I found that I could get around the issue by restarting, running UD first, then importing/connecting to MSonline. Just a workaround, and it seems to still be an issue as of UD v2.5.3. Hope this helps
