### ISSUE TITLE
Error while loading UD 2.4 on raspbian

### ISSUE THREAD

**Issue by DanielSSilva** [ironmansoftware/universal-dashboard#831]
Upon installing version 2.4, When I first try to load the module it throws an error saying it can find a path, but after trying to import again it loads fine.
![image](https://user-images.githubusercontent.com/6862119/58361053-edfb5d80-7e83-11e9-9460-bcb3aa76b421.png)

Also tried with 2.4 beta , but this one throws another error (on EndpointInitialization)
![image](https://user-images.githubusercontent.com/6862119/58361079-171bee00-7e84-11e9-950c-1431425cac82.png)

Unsure if this is related, but after loading the module for the second time and it loads successfully(the 2.4, not the beta) , when I try to run my script it says that the New-UDRow " is not recognized as the name of a cmdlet, function, script file, or operable program.".

The very same script works fine with 2.3.2

**Comment by leeberg** [comment]
Did some testing with Raspbian installed the latest community, then went ahead and tried to run the poshhud example. Errors were thrown on dashboard start, but the dashboard did start and some elements did load OK. While traversing pages it continued to throw errors.

**PowerShell Version**: powershell-6.2.1-linux-arm32.tar.gz


```
PS /home/pi/universal-dashboard/examples> ./poshud.ps1
Exception while loading assembly Microsoft.Extensions.Logging.Filter:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.Extensions.Logging.Filter.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.Extensions.Logging.Filter.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Exception while loading assembly Microsoft.Extensions.Logging.Filter:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.Extensions.Logging.Filter.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.Extensions.Logging.Filter.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Hosting environment: Production
Content root path: /usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/../client
Now listening on: http://0.0.0.0:10001
Application started. Press Ctrl+C to shut down.
```


**MORE ERRORS WHEN Browsing the UD Page**

```
PS /home/pi/universal-dashboard/examples> ./poshud.ps1                          Exception while loading assembly Microsoft.AspNetCore.DataProtection.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Exception while loading assembly Microsoft.AspNetCore.DataProtection.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Exception while loading assembly Microsoft.Extensions.Logging.Filter:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.Extensions.Logging.Filter.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.Extensions.Logging.Filter.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Exception while loading assembly Microsoft.AspNetCore.Mvc.Abstractions.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Exception while loading assembly Microsoft.AspNetCore.Mvc.Abstractions.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Hosting environment: Production
Content root path: /usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/../client
Now listening on: http://0.0.0.0:10001
Application started. Press Ctrl+C to shut down.
Exception while loading assembly Microsoft.AspNetCore.Server.Kestrel.Core.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Server.Kestrel.Core.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Server.Kestrel.Core.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Exception while loading assembly Microsoft.AspNetCore.Server.Kestrel.Core.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Server.Kestrel.Core.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/Microsoft.AspNetCore.Server.Kestrel.Core.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209


Exception while loading assembly System.Threading.Tasks.Channels.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/System.Threading.Tasks.Channels.resources.dll'. The system cannot find the file specified.

File name: '/usr/local/share/powershell/Modules/UniversalDashboard/1.5.0/netcoreapp2.0/System.Threading.Tasks.Channels.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 209

```
