### ISSUE TITLE
Error running on Raspbian (Stretch)

### ISSUE THREAD

**Issue by GavinEke** [ironmansoftware/universal-dashboard#84]
Error when attempting to run UniversalDashboard on Raspbian (Stretch)

PowerShell Version: 6.0.2
UniversalDashboard Version: 1.5.3

```
Exception while loading assembly Microsoft.AspNetCore.DataProtection.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'. The system cannot find the file specified.

File name: '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182


Exception while loading assembly Microsoft.AspNetCore.DataProtection.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'. The system cannot find the file specified.

File name: '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.DataProtection.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182


Exception while loading assembly Microsoft.AspNetCore.Mvc.Abstractions.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'. The system cannot find the file specified.

File name: '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182


Exception while loading assembly Microsoft.AspNetCore.Mvc.Abstractions.resources:

System.IO.FileNotFoundException: Could not load file or assembly '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'. The system cannot find the file specified.

File name: '/home/pi/.local/share/powershell/Modules/UniversalDashboard/1.5.3/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at PowerShellProTools.UniversalDashboard.Server.OnAssemblyResolve(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\1\s\PowerShellProTools.UniversalDashboard\Server\Server.cs:line 182



Name       Port Running
----       ---- -------
Dashboard0 8080    True

```

**Comment by adamdriscoll** [comment]
@GavinEke Is the dashboard usable? I've seen errors like this but everything still works. I still plan on fixing it but want to know the impact so I can stack rank.

**Comment by GavinEke** [comment]
Yes you are right it does still appear to work, so impact is low.
